#!/bin/sh

### BEGIN INIT INFO
# Provides:        autoboiler
# Required-Start:  $syslog
# Required-Stop:   $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    0 1 6
# Short-Description: Start Autoboiler daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/home/pi/src/autoboiler/autoboiler.py
PIDFILE=/var/run/autoboiler.pid

test -x $DAEMON || exit 5

if [ -r /etc/default/autoboiler ]; then
	. /etc/default/autoboiler
fi

LOCKFILE=/var/lock/autoboiler

lock_autoboiler() {
	if [ -x /usr/bin/lockfile-create ]; then
		lockfile-create $LOCKFILE
		lockfile-touch $LOCKFILE &
		LOCKTOUCHPID="$!"
	fi
}

unlock_autoboiler() {
	if [ -x /usr/bin/lockfile-create ] ; then
		kill $LOCKTOUCHPID
		lockfile-remove $LOCKFILE
	fi
}

case $1 in
	start)
		log_daemon_msg "Starting Autoboiler daemon" "autoboiler"
		#lock_autoboiler
  		start-stop-daemon -b --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE $AUTOBOILER_OPTS
		status=$?
		#unlock_autoboiler
		log_end_msg $status
  		;;
	stop)
		log_daemon_msg "Stopping Autoboiler daemon" "autoboiler"
  		start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
		log_end_msg $?
		rm -f $PIDFILE
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "Autoboiler daemon"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
